// <auto-generated />
using System;
using System.Collections.Generic;
using GetJobAI.Optimisation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GetJobAI.Optimisation.Migrations
{
    [DbContext(typeof(OptimisationDbContext))]
    partial class OptimisationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GetJobAI.Optimisation.Data.Entities.Optimisation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AtsDetailsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("ats_details");

                    b.Property<string>("AtsExplanation")
                        .HasColumnType("jsonb")
                        .HasColumnName("ats_explanation");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("company_name");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<Guid>("JobAnalysisId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_analysis_id");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("job_title");

                    b.Property<int>("OverallScore")
                        .HasColumnType("integer")
                        .HasColumnName("overall_score");

                    b.Property<Guid>("ResumeId")
                        .HasColumnType("uuid")
                        .HasColumnName("resume_id");

                    b.Property<short>("ScoreExperienceEarned")
                        .HasColumnType("smallint")
                        .HasColumnName("score_experience_earned");

                    b.Property<short>("ScoreExperienceMax")
                        .HasColumnType("smallint")
                        .HasColumnName("score_experience_max");

                    b.Property<short>("ScoreFormatEarned")
                        .HasColumnType("smallint")
                        .HasColumnName("score_format_earned");

                    b.Property<short>("ScoreFormatMax")
                        .HasColumnType("smallint")
                        .HasColumnName("score_format_max");

                    b.Property<short>("ScoreKeywordEarned")
                        .HasColumnType("smallint")
                        .HasColumnName("score_keyword_earned");

                    b.Property<short>("ScoreKeywordMax")
                        .HasColumnType("smallint")
                        .HasColumnName("score_keyword_max");

                    b.Property<short>("ScoreSkillEarned")
                        .HasColumnType("smallint")
                        .HasColumnName("score_skill_earned");

                    b.Property<short>("ScoreSkillMax")
                        .HasColumnType("smallint")
                        .HasColumnName("score_skill_max");

                    b.Property<string>("SkillsGap")
                        .HasColumnType("jsonb")
                        .HasColumnName("skills_gap");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_optimisations_created_at");

                    b.HasIndex("JobAnalysisId")
                        .HasDatabaseName("ix_optimisations_job_analysis_id");

                    b.HasIndex("ResumeId")
                        .HasDatabaseName("ix_optimisations_resume_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_optimisations_status");

                    b.ToTable("optimisations", (string)null);
                });

            modelBuilder.Entity("GetJobAI.Optimisation.Data.Entities.OptimisationActivitySuggestion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool?>("Accepted")
                        .HasColumnType("boolean")
                        .HasColumnName("accepted");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("entry_id");

                    b.PrimitiveCollection<List<string>>("HighlightsRewritten")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("highlights_rewritten");

                    b.Property<bool>("Include")
                        .HasColumnType("boolean")
                        .HasColumnName("include");

                    b.Property<Guid>("OptimisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("optimisation_id");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("RejectionHint")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("rejection_hint");

                    b.Property<int>("RewriteCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("rewrite_count");

                    b.HasKey("Id");

                    b.HasIndex("OptimisationId", "EntryId")
                        .IsUnique()
                        .HasDatabaseName("ix_optimisation_activity_suggestions_optimisation_entry");

                    b.ToTable("optimisation_activity_suggestions", (string)null);
                });

            modelBuilder.Entity("GetJobAI.Optimisation.Data.Entities.OptimisationBulletSuggestion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool?>("Accepted")
                        .HasColumnType("boolean")
                        .HasColumnName("accepted");

                    b.PrimitiveCollection<List<string>>("KeywordsAdded")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("keywords_added");

                    b.Property<string>("Original")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original");

                    b.Property<string>("Rewritten")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rewritten");

                    b.Property<Guid>("WorkExperienceSuggestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_experience_suggestion_id");

                    b.Property<bool>("XyzApplied")
                        .HasColumnType("boolean")
                        .HasColumnName("xyz_applied");

                    b.HasKey("Id");

                    b.HasIndex("WorkExperienceSuggestionId")
                        .HasDatabaseName("ix_optimisation_bullet_suggestions_work_experience_id");

                    b.ToTable("optimisation_bullet_suggestions", (string)null);
                });

            modelBuilder.Entity("GetJobAI.Optimisation.Data.Entities.OptimisationCoverLetter", b =>
                {
                    b.Property<Guid>("OptimisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("optimisation_id");

                    b.Property<bool?>("Accepted")
                        .HasColumnType("boolean")
                        .HasColumnName("accepted");

                    b.Property<string>("CoverLetter")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cover_letter");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.PrimitiveCollection<List<string>>("KeyPointsMade")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("key_points_made");

                    b.Property<int>("RewriteCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("rewrite_count");

                    b.Property<string>("SalutationUsed")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("salutation_used");

                    b.Property<int>("WordCount")
                        .HasColumnType("integer")
                        .HasColumnName("word_count");

                    b.HasKey("OptimisationId");

                    b.ToTable("optimisation_cover_letters", (string)null);
                });

            modelBuilder.Entity("GetJobAI.Optimisation.Data.Entities.OptimisationSectionSuggestion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool?>("Accepted")
                        .HasColumnType("boolean")
                        .HasColumnName("accepted");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("category");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("entry_id");

                    b.Property<bool>("Include")
                        .HasColumnType("boolean")
                        .HasColumnName("include");

                    b.Property<Guid>("OptimisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("optimisation_id");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("SectionType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("section_type");

                    b.HasKey("Id");

                    b.HasIndex("OptimisationId", "Category", "EntryId")
                        .IsUnique()
                        .HasDatabaseName("ix_optimisation_section_suggestions_optimisation_category_entry");

                    b.ToTable("optimisation_section_suggestions", (string)null);
                });

            modelBuilder.Entity("GetJobAI.Optimisation.Data.Entities.OptimisationSummarySuggestion", b =>
                {
                    b.Property<Guid>("OptimisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("optimisation_id");

                    b.Property<bool?>("Accepted")
                        .HasColumnType("boolean")
                        .HasColumnName("accepted");

                    b.PrimitiveCollection<List<string>>("KeywordsIncorporated")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("keywords_incorporated");

                    b.Property<string>("Original")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original");

                    b.Property<string>("RejectionHint")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("rejection_hint");

                    b.Property<int>("RewriteCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("rewrite_count");

                    b.Property<string>("Rewritten")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rewritten");

                    b.HasKey("OptimisationId");

                    b.ToTable("optimisation_summary_suggestions", (string)null);
                });

            modelBuilder.Entity("GetJobAI.Optimisation.Data.Entities.OptimisationWorkExperienceSuggestion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool?>("Accepted")
                        .HasColumnType("boolean")
                        .HasColumnName("accepted");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("entry_id");

                    b.Property<bool>("Include")
                        .HasColumnType("boolean")
                        .HasColumnName("include");

                    b.Property<Guid>("OptimisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("optimisation_id");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("RejectionHint")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("rejection_hint");

                    b.Property<int>("RewriteCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("rewrite_count");

                    b.HasKey("Id");

                    b.HasIndex("OptimisationId", "EntryId")
                        .IsUnique()
                        .HasDatabaseName("ix_optimisation_work_experience_suggestions_optimisation_entry");

                    b.ToTable("optimisation_work_experience_suggestions", (string)null);
                });

            modelBuilder.Entity("GetJobAI.Optimisation.Data.Entities.Resume", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("resumes", null, t => t.ExcludeFromMigrations());
                });

            modelBuilder.Entity("GetJobAI.Optimisation.Data.Entities.OptimisationActivitySuggestion", b =>
                {
                    b.HasOne("GetJobAI.Optimisation.Data.Entities.Optimisation", "Optimisation")
                        .WithMany("ActivitySuggestions")
                        .HasForeignKey("OptimisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Optimisation");
                });

            modelBuilder.Entity("GetJobAI.Optimisation.Data.Entities.OptimisationBulletSuggestion", b =>
                {
                    b.HasOne("GetJobAI.Optimisation.Data.Entities.OptimisationWorkExperienceSuggestion", "WorkExperienceSuggestion")
                        .WithMany("Bullets")
                        .HasForeignKey("WorkExperienceSuggestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkExperienceSuggestion");
                });

            modelBuilder.Entity("GetJobAI.Optimisation.Data.Entities.OptimisationCoverLetter", b =>
                {
                    b.HasOne("GetJobAI.Optimisation.Data.Entities.Optimisation", "Optimisation")
                        .WithOne("CoverLetter")
                        .HasForeignKey("GetJobAI.Optimisation.Data.Entities.OptimisationCoverLetter", "OptimisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Optimisation");
                });

            modelBuilder.Entity("GetJobAI.Optimisation.Data.Entities.OptimisationSectionSuggestion", b =>
                {
                    b.HasOne("GetJobAI.Optimisation.Data.Entities.Optimisation", "Optimisation")
                        .WithMany("SectionSuggestions")
                        .HasForeignKey("OptimisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Optimisation");
                });

            modelBuilder.Entity("GetJobAI.Optimisation.Data.Entities.OptimisationSummarySuggestion", b =>
                {
                    b.HasOne("GetJobAI.Optimisation.Data.Entities.Optimisation", "Optimisation")
                        .WithOne("SummarySuggestion")
                        .HasForeignKey("GetJobAI.Optimisation.Data.Entities.OptimisationSummarySuggestion", "OptimisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Optimisation");
                });

            modelBuilder.Entity("GetJobAI.Optimisation.Data.Entities.OptimisationWorkExperienceSuggestion", b =>
                {
                    b.HasOne("GetJobAI.Optimisation.Data.Entities.Optimisation", "Optimisation")
                        .WithMany("WorkExperienceSuggestions")
                        .HasForeignKey("OptimisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Optimisation");
                });

            modelBuilder.Entity("GetJobAI.Optimisation.Data.Entities.Optimisation", b =>
                {
                    b.Navigation("ActivitySuggestions");

                    b.Navigation("CoverLetter");

                    b.Navigation("SectionSuggestions");

                    b.Navigation("SummarySuggestion");

                    b.Navigation("WorkExperienceSuggestions");
                });

            modelBuilder.Entity("GetJobAI.Optimisation.Data.Entities.OptimisationWorkExperienceSuggestion", b =>
                {
                    b.Navigation("Bullets");
                });
#pragma warning restore 612, 618
        }
    }
}
